version: '3'

services:
  toyshare:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Development service with hot-reloading
  toyshare-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--experimental-json-modules --no-warnings
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev